version: '3.8'

services:
  test-001-search:
    build: .
    container_name: test-001-search
    ports:
      - "8000:8000"
    volumes:
      # Mount data directory for persistence (optional - data is already copied in build)
      - ./data:/app/data:ro
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: test-001-network